---
title: "dryland_vegetation_restoration"
author: "MFM"
date: "26 de octubre de 2018"
output: html_document
---

## R Markdown

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

```{r initialize, echo= T, message= FALSE, warning= F}

library(tidyverse)
library(RColorBrewer)

```

##Summarize extracted data

```{r input}

data<- read.csv("~/GitHub/dryland_restoration_synthesis/data/data.csv", header= T, sep= ",",
                dec = ".", na.strings = "NA")
str(data)

```

```{r select 26 articles}

#ID: 1,2,3,4,5,6,9,11,12,13,15,16,19,20,21,64,77,78,86,87,88,89,91,95,98,104 articles with data extracted

mydata<- data %>% 
  dplyr::filter(study.ID %in% c(1,2,3,4,5,6,9,11,12,13,15,16,19,20,21,64,77,78,86,87,88,89,91,95,98,104))

#%>%  
 # dplyr::select(1:13,31:35) 

#mydata

#mydata$study.ID

#class(data$study.ID)
```

```{r}

#where

require(maps)

world<-map_data("world")

map<-ggplot() + geom_polygon(data=world, fill="gray50", aes(x=long, y=lat, group=group))
map + geom_point(data=mydata, aes(x=long, y=lat)) 



mydata.simple1 <- mydata %>% group_by(continent, country, study.ID) %>% count()
mydata.simple2 <- mydata.simple1 %>% group_by(continent, country) %>% count()
ggplot(na.omit(mydata.simple2), aes(continent,nn, fill=country))+ geom_bar(stat = "identity") + coord_flip(ylim=0:25) +scale_fill_brewer(palette ="Spectral")


#mydata.simple1
#mydata.simple2
```

```{r}
#why

mydata.simple3 <- mydata %>% group_by(disturbance, ecosystem, study.ID) %>% count()
mydata.simple4 <- mydata.simple3 %>% group_by(disturbance, ecosystem) %>% count()
ggplot(na.omit(mydata.simple4), aes(disturbance,nn, fill=ecosystem)) + geom_bar(stat = "identity") + coord_flip(ylim=0:25) + scale_fill_brewer(palette = "Blues")

#mydata.simple3
#mydata.simple4


mydata.simple5 <- mydata %>% group_by(technique, focus, study.ID) %>% count()
mydata.simple6 <- mydata.simple5 %>% group_by(technique, focus) %>% count()
ggplot(na.omit(mydata.simple6), aes(technique,nn, fill=focus)) + geom_bar(stat = "identity") + coord_flip(ylim=0:25) + scale_fill_brewer(palette = "Blues")

#mydata.simple5
#mydata.simple6


mydata.simple7 <- mydata %>% group_by(continent, paradigm, study.ID) %>% count()
mydata.simple8 <- mydata.simple7 %>% group_by(continent, paradigm) %>% count()
ggplot(na.omit(mydata.simple8), aes(continent,nn, fill=paradigm)) + geom_bar(stat = "identity") + coord_flip(ylim=0:25) + scale_fill_brewer(palette = "Blues")

#mydata.simple7
#mydata.simple8

mydata.simple9 <- mydata %>% group_by(publication.year,study.ID) %>% count()
mydata.simple10 <- mydata.simple9 %>% group_by(publication.year) %>% count()
ggplot(mydata.simple10, aes(x=publication.year, y=nn)) + geom_point() + xlim (2002, 2018)


#mydata.simple9
#mydata.simple10

mydata.simple11 <- mydata %>% group_by(disturbance, technique, study.ID) %>% count()
mydata.simple12 <- mydata.simple11 %>% group_by(disturbance, technique) %>% count()

mycolors = c(brewer.pal(name="Set3", n = 12), brewer.pal(name="Paired", n = 12))

ggplot(na.omit(mydata.simple12), aes(disturbance,nn, fill=technique)) + geom_bar(stat = "identity") + coord_flip(ylim=0:25) + scale_fill_manual(values = mycolors)


mydata.simple13 <- mydata %>% group_by(disturbance, focus, study.ID) %>% count()
mydata.simple14 <- mydata.simple13 %>% group_by(disturbance, focus) %>% count()
ggplot(na.omit(mydata.simple14), aes(disturbance,nn, fill=focus)) + geom_bar(stat = "identity") + coord_flip(ylim=0:25) + scale_fill_brewer(palette = "Blues")

mydata.simple15 <- mydata %>% group_by(control, study.ID) %>% count()
mydata.simple16<- mydata.simple15 %>% group_by(control) %>% count()
ggplot(na.omit(mydata.simple16), aes(control,nn)) + geom_bar(stat = "identity") + coord_flip(ylim=0:25) 


#mydata.simple15
#mydata.simple16

mydata.simple17 <- mydata %>% group_by(measure.success, study.ID) %>% count()
mydata.simple18<- mydata.simple17 %>% group_by(measure.success) %>% count()
ggplot(na.omit(mydata.simple18), aes(measure.success,nn)) + geom_bar(stat = "identity") + coord_flip(ylim=0:25) 


```


